-- +goose Up
CREATE TABLE IF NOT EXISTS users(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    balance numeric NOT NULL CHECK (balance >= 0),
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transactions(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    date bigint NOT NULL,
    type integer NOT NULL,
    user_id integer NOT NULL,
    comment text NOT NULL,
    sum numeric NOT NULL CHECK (sum > 0),
    CONSTRAINT "PK_transactions" PRIMARY KEY (id),
    CONSTRAINT "FK_users_user_id" FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS transaction__date__index ON transactions (date);

INSERT INTO users (name, balance) VALUES ('Василий', 1000);
INSERT INTO users (name, balance) VALUES ('Николай', 0);
INSERT INTO users (name, balance) VALUES ('Екатерина', 5);


-- +goose Down
DROP INDEX IF EXISTS transaction__date__index;
DROP TABLE IF NOT EXISTS users;
DROP TABLE IF NOT EXISTS transactions;